DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_type VARCHAR(250) NOT NULL,
    product_name VARCHAR(250) NOT NULL,
    author VARCHAR(250) NOT NULL,
    price INT NOT NULL,
    img VARCHAR(250) NOT NULL,
    about VARCHAR(1000) NOT NULL
)